# Generated by Django 2.1.5 on 2019-03-26 13:02

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0003_auto_20190326_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='members', through='teams.TeamMember', to=settings.AUTH_USER_MODEL),
        ),
    ]
