# Generated by Django 2.1.5 on 2019-03-26 13:16

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('teams', '0004_team_members'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='user',
            new_name='member',
        ),
        migrations.AlterUniqueTogether(
            name='teammember',
            unique_together={('team', 'member')},
        ),
    ]
