# Generated by Django 2.1.5 on 2019-03-26 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0007_team_members'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
