# Generated by Django 2.1.5 on 2019-03-27 15:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0009_auto_20190326_2024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='creator',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userteam', to=settings.AUTH_USER_MODEL),
        ),
    ]
