# Generated by Django 2.1.5 on 2019-03-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_auto_20190329_1009'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creater',
            new_name='creator',
        ),
    ]
