# Generated by Django 2.1.5 on 2019-03-29 17:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tasks', '0003_auto_20190329_1511'),
    ]

    operations = [
        migrations.RenameField(
            model_name='taskassignees',
            old_name='user',
            new_name='assignee',
        ),
        migrations.AlterUniqueTogether(
            name='taskassignees',
            unique_together={('task', 'assignee')},
        ),
    ]
