# Generated by Django 2.1.5 on 2019-03-29 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_auto_20190329_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskteam',
            name='team',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='team', to='teams.Team'),
        ),
    ]
