# Generated by Django 2.1.5 on 2019-03-31 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0010_auto_20190331_1842'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='user',
            new_name='creator',
        ),
    ]
