# Generated by Django 2.1.1 on 2019-03-31 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0014_comment_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='slug',
            field=models.SlugField(allow_unicode=True, unique=True),
        ),
    ]
